services:
  mysql:
    image: mysql:8.0
    container_name: mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-2
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  mysql_data: